adding comments to code
weirdsir/tools_course pull request #6
Opened 2024-04-10 19:03 UTC by yoinkeds

2024-04-10 20:35 UTC, dkrpv requested changes
Irrelevant comments

2024-04-11 19:03 UTC, weirdsir requested changes
maybe we need more comments

2024-04-15 16:42 UTC, dkrpv approved these changes
Comments relevant, representing the code

2024-04-17 16:53 UTC, weirdsir approved these changes
amazing comments

2024-04-17 16:54 UTC, merged